# Generated by Django 5.0.6 on 2024-06-01 19:48

import apps.room.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('RoomName', models.CharField(max_length=255)),
                ('Slug', models.SlugField(max_length=255, unique=True)),
                ('Thumbnail', models.ImageField(upload_to=apps.room.models.room_thumbnail_directory)),
                ('Excerpt', models.CharField(max_length=255)),
                ('Description', ckeditor.fields.RichTextField()),
                ('RoomPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('RoomNumber', models.IntegerField()),
                ('Status', models.CharField(max_length=30)),
                ('Views', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_view_count', to='room.room')),
            ],
        ),
    ]
