# Generated by Django 5.0.6 on 2024-06-01 19:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Excerpt',
        ),
        migrations.AddField(
            model_name='room',
            name='Content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='Description',
            field=models.CharField(max_length=255),
        ),
    ]
