# Generated by Django 5.0.6 on 2024-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_excerpt_room_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Description',
            field=models.TextField(max_length=255),
        ),
    ]
