# Generated by Django 5.0.6 on 2024-06-01 20:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
