# Generated by Django 5.0.6 on 2024-06-01 21:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
