# Generated by Django 5.0.6 on 2024-06-01 21:58

import apps.room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Thumbnail',
            field=models.ImageField(max_length=500, upload_to=apps.room.models.room_thumbnail_directory),
        ),
    ]
