# Generated by Django 5.0.6 on 2024-06-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_room_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-RoomName',)},
        ),
    ]
