export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS';
export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL';
export const GET_ROOM_LIST_CATEGORIES_SUCCESS = 'GET_ROOM_LIST_CATEGORIES_SUCCESS';
export const GET_ROOM_LIST_CATEGORIES_FAIL = 'GET_ROOM_LIST_CATEGORIES_FAIL';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAIL = 'GET_ROOM_FAIL';
export const GET_SEARCH_ROOM_SUCCESS = 'GET_SEARCH_ROOM_SUCCESS';
export const GET_SEARCH_ROOM_FAIL = 'GET_SEARCH_ROOM_FAIL';
